import type { Property, Neighborhood, TeamMember, Service, Stat, NavLink } from "@/types";

export const SITE_NAME = "Lodhi Estates";
export const SITE_TAGLINE = "Where Nature Meets Quiet Luxury";
export const SITE_DESCRIPTION =
  "Curated private portfolio of prime architectural residences, cantilevered glass pavilions, and coastal sanctuaries.";

export const NAV_LINKS: NavLink[] = [
  { label: "Collection", href: "/properties" },
  { label: "Heritage", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Locations", href: "/neighborhoods" },
  { label: "Contact", href: "/contact" },
];

export const PROPERTIES: Property[] = [
  {
    id: "prop-1",
    slug: "villa-solaria-coastal",
    title: "Villa Solaria & Travertine Terraces",
    headline: "Minimalist Coastal Promontory with Infinite Sea Vistas",
    location: "Cala Del Mar, Mediterranean Heights",
    neighborhood: "Mediterranean Heights",
    city: "Mediterranean Coast",
    price: "$9,450,000",
    priceNumeric: 9450000,
    type: "Villa",
    status: "For Sale",
    bedrooms: 5,
    bathrooms: 6,
    area: "6,400 sq ft",
    sqftNumeric: 6400,
    lotSize: "1.8 Acres of White Travertine Grounds",
    yearBuilt: 2024,
    garage: "4-Car Underground Showroom",
    image: "/images/hero-bright-villa.jpg",
    gallery: [
      "/images/hero-bright-villa.jpg",
      "/images/hero-velora.jpg",
      "/images/hero-sovex.jpg",
      "/images/property-2.jpg",
    ],
    tag: "Signature Masterwork",
    description:
      "Hovering above the azure Mediterranean shoreline, Villa Solaria is sculpted in monolithic Roman travertine and frameless structural glass. Features include a shallow reflection pool with floating travertine steps, centuries-old sculptural olive trees, zero-threshold sliding apertures, and an open-concept living pavilion embracing infinite horizon views.",
    highlights: [
      "Monolithic honed Roman travertine terraces and seamless interior flooring",
      "Floating travertine stepping stones across heated reflection pool",
      "Floor-to-ceiling Schuco glass walls disappearing completely into hidden pockets",
      "Private cliffside wine tasting cellar and master suite with outdoor stone tub",
    ],
    amenities: [
      "Heated Reflection Pool",
      "Centuries-Old Olive Grove",
      "Wine Tasting Cellar",
      "Zero-Threshold Glass",
      "Smart Geothermal HVAC",
      "Private Security Gated",
    ],
    features: {
      architecturalStyle: "Contemporary Monolithic Travertine",
      view: "Unobstructed Mediterranean Shoreline & Horizon",
      heatingCooling: "Concealed Geothermal Underfloor Radiant",
      security: "Biometric Compound Access & 24/7 Security Desk",
    },
    agent: {
      name: "Elena Rostova",
      role: "Senior Partner, Architectural Estates",
      phone: "+1 (555) 920-8422",
      email: "elena.rostova@lodhiestates.com",
      image: "/images/about.jpg",
    },
  },
  {
    id: "prop-2",
    slug: "velora-sanctuary-pavilion",
    title: "Velora Sanctuary & Forest Pavilion",
    headline: "Harmonious Glass Residence Nestled in Misty Hillside",
    location: "Pine Crest Promenade, Royal Gardens",
    neighborhood: "Royal Gardens",
    city: "California Coast",
    price: "$8,750,000",
    priceNumeric: 8750000,
    type: "Villa",
    status: "For Sale",
    bedrooms: 6,
    bathrooms: 7,
    area: "7,800 sq ft",
    sqftNumeric: 7800,
    lotSize: "2.4 Acres of Native Flora",
    yearBuilt: 2024,
    garage: "3-Car Portico + Motor Court",
    image: "/images/hero-velora.jpg",
    gallery: [
      "/images/hero-velora.jpg",
      "/images/hero-bright-villa.jpg",
      "/images/hero-sovex.jpg",
      "/images/property-1.jpg",
    ],
    tag: "Private Villa Retreat",
    description:
      "A triumph of organic minimalism. Velora Pavilion integrates board-formed concrete, warm cedar ceilings, and living green rooflines. Frameless glass apertures open onto a floating cantilevered infinity pool reflecting mist-shrouded mountain ridges at twilight.",
    highlights: [
      "Integrated living sedum green roof providing natural thermal insulation",
      "70ft black basalt infinity pool cantilevered over the private valley",
      "Custom Italian walnut millwork with concealed flush-to-wall cabinetry",
      "Private wellness pavilion with Finnish sauna and sunken stone lounge",
    ],
    amenities: [
      "70ft Cantilevered Pool",
      "Living Green Roof",
      "Finnish Cedar Sauna",
      "Integrated Soundscape",
      "Private Wellness Pavilion",
      "24/7 Monitored Estate",
    ],
    features: {
      architecturalStyle: "Organic Modernist Concrete & Timber",
      view: "Misty Mountain Ridges & Valley Pine Groves",
      heatingCooling: "Passive Solar & Multi-Zone Radiant Heat",
      security: "Encrypted Perimeter Infrared & Gated Entry",
    },
    agent: {
      name: "Lord A. Lodhi",
      role: "Founder & Senior Principal",
      phone: "+1 (555) 920-8401",
      email: "lodhi@lodhiestates.com",
      image: "/images/about.jpg",
    },
  },
  {
    id: "prop-3",
    slug: "the-cantilever-glass-house",
    title: "The Glass & Timber Cantilever",
    headline: "Ultra-Modern Architectural Pavilion Surrounded by Pines",
    location: "Highland Crest, Greenfield",
    neighborhood: "Greenfield Estates",
    city: "Pacific Northwest",
    price: "$6,900,000",
    priceNumeric: 6900000,
    type: "Villa",
    status: "For Sale",
    bedrooms: 5,
    bathrooms: 5,
    area: "5,800 sq ft",
    sqftNumeric: 5800,
    lotSize: "1.5 Acres Manicured Pine Gardens",
    yearBuilt: 2024,
    garage: "3-Car Climate Controlled Garage",
    image: "/images/hero-sovex.jpg",
    gallery: [
      "/images/hero-sovex.jpg",
      "/images/hero-bright-villa.jpg",
      "/images/property-2.jpg",
      "/images/property-3.jpg",
    ],
    tag: "Intelligent Architecture",
    description:
      "Bold horizontal overhangs crafted in western red cedar float above structural glass walls. Designed around a central courtyard featuring a tranquil lap pool, sculptural limestone paths, and double-height living spaces flooded with natural northern light.",
    highlights: [
      "Cantilevered cedar roof overhangs creating shaded outdoor loggias",
      "Central lap pool with natural slate stepping stones and water weir",
      "Double quartzite chef's show kitchen with Gaggenau 400 Series appliances",
      "Separate self-contained guest studio with private garden access",
    ],
    amenities: [
      "Heated Lap Pool",
      "Outdoor Sunken Fire Pit",
      "Smart Solar Glass",
      "Custom Travertine Hearth",
      "Bespoke Italian Kitchen",
      "EV Charging Stations",
    ],
    features: {
      architecturalStyle: "Mid-Century Modernist Cantilever",
      view: "Manicured Pines & Mountain Promontory",
      heatingCooling: "High-Efficiency Geothermal Heat Pump",
      security: "Full Video Intercom & Biometric Gate",
    },
    agent: {
      name: "Marcus Vance",
      role: "Managing Director, Prime Residences",
      phone: "+1 (555) 920-8411",
      email: "marcus.vance@lodhiestates.com",
      image: "/images/about.jpg",
    },
  },
  {
    id: "prop-4",
    slug: "the-nordic-modular-retreat",
    title: "The Nordic Timber Retreat",
    headline: "Bespoke Off-Site Modular Masterwork Delivered in 45 Days",
    location: "Mist Ridge Pass, Greenfield",
    neighborhood: "Greenfield Estates",
    city: "Pacific Northwest",
    price: "$3,650,000",
    priceNumeric: 3650000,
    type: "Modern Modular",
    status: "For Sale",
    bedrooms: 4,
    bathrooms: 3,
    area: "3,400 sq ft",
    sqftNumeric: 3400,
    lotSize: "3.0 Acres Mountain Woodland",
    yearBuilt: 2024,
    garage: "2-Car Timber Carport",
    image: "/images/hero-modul.jpg",
    gallery: [
      "/images/hero-modul.jpg",
      "/images/hero-sovex.jpg",
      "/images/property-3.jpg",
      "/images/neighborhood-3.jpg",
    ],
    tag: "Turnkey Modular (45 Days)",
    description:
      "Constructed off-site with sub-millimeter precision and delivered turnkey. Crafted from charred Yakisugi cedar, natural dry-stacked fieldstone, and quadruple-glazed acoustical glass. Net-zero energy certification with off-grid Tesla Powerwall storage.",
    highlights: [
      "Turnkey 30-60 day on-site assembly with zero contractor delay or site disruption",
      "Suspended steel focus fireplace warming the double-height timber great room",
      "Expansive cantilevered cedar viewing deck overlooking alpine mist",
      "Finnish cedar hot barrel and cold plunge overlooking mountain valleys",
    ],
    amenities: [
      "Finnish Sauna & Plunge",
      "Tesla Powerwall Solar",
      "Suspended Iron Hearth",
      "Quadruple-Glazed Glass",
      "Dry-Stacked Stone Walls",
      "Fully Furnished Turnkey",
    ],
    features: {
      architecturalStyle: "Scandinavian Minimalist Modular",
      view: "Alpine Mountain Mist & Woodland",
      heatingCooling: "Passivhaus A+ Geothermal System",
      security: "Satellite Monitored Smart Access",
    },
    agent: {
      name: "Julian Thorne",
      role: "Director, Turnkey & Off-Market Acquisitions",
      phone: "+1 (555) 920-8433",
      email: "julian.thorne@lodhiestates.com",
      image: "/images/about.jpg",
    },
  },
  {
    id: "prop-5",
    slug: "the-skyline-penthouse",
    title: "The Marina Duplex Penthouse",
    headline: "Sky-High Duplex with 360° Harbor & City Skyline Panorama",
    location: "One Marina Plaza, Marina Bay",
    neighborhood: "Marina Bay",
    city: "New York",
    price: "$4,850,000",
    priceNumeric: 4850000,
    type: "Penthouse",
    status: "For Sale",
    bedrooms: 4,
    bathrooms: 4,
    area: "4,200 sq ft",
    sqftNumeric: 4200,
    lotSize: "Private Sky Terrace (1,400 sq ft)",
    yearBuilt: 2023,
    garage: "2 Underground Deeded Bays + Private Lift",
    image: "/images/property-1.jpg",
    gallery: [
      "/images/property-1.jpg",
      "/images/hero-bright-villa.jpg",
      "/images/property-3.jpg",
      "/images/neighborhood-2.jpg",
    ],
    tag: "Exclusive Penthouse",
    description:
      "Hovering above the marina harbor, this duplex residence features 20ft double-height ceiling voids, private high-speed elevator access, bespoke Calacatta gold marble fireplaces, and a wraparound terrace with heated outdoor plunge pool.",
    highlights: [
      "Direct key-card private elevator opening into private gallery foyer",
      "Heated rooftop infinity plunge pool with skyline harbor views",
      "Poliform Italian kitchen with concealed prep scullery",
      "Primary dressing room wrapped in suede panels and custom lighting",
    ],
    amenities: [
      "Private Sky Terrace",
      "Rooftop Plunge Pool",
      "Private Lift Access",
      "24/7 White-Glove Doorman",
      "Direct Marina Berth",
      "Private Wine Locker",
    ],
    features: {
      architecturalStyle: "Contemporary High-Rise Duplex",
      view: "360° Marina Harbor & Skyline",
      heatingCooling: "Multi-Zone Geothermal Climate Control",
      security: "Biometric Elevator & 24/7 Concierge",
    },
    agent: {
      name: "Marcus Vance",
      role: "Managing Director, Prime Residences",
      phone: "+1 (555) 920-8411",
      email: "marcus.vance@lodhiestates.com",
      image: "/images/about.jpg",
    },
  },
  {
    id: "prop-6",
    slug: "villa-serena-estate",
    title: "Villa Serena & Coastal Bluff",
    headline: "Grand Contemporary Mediterranean Estate on Cliff Edge",
    location: "Promontory Vista, Mediterranean Heights",
    neighborhood: "Mediterranean Heights",
    city: "California Coast",
    price: "$7,200,000",
    priceNumeric: 7200000,
    type: "Villa",
    status: "Exclusive Off-Market",
    bedrooms: 6,
    bathrooms: 6,
    area: "7,500 sq ft",
    sqftNumeric: 7500,
    lotSize: "2.2 Acres Private Promontory",
    yearBuilt: 2023,
    garage: "4-Car Underground Gallery",
    image: "/images/property-2.jpg",
    gallery: [
      "/images/property-2.jpg",
      "/images/hero-bright-villa.jpg",
      "/images/property-1.jpg",
      "/images/neighborhood-1.jpg",
    ],
    tag: "Off-Market Trophy",
    description:
      "Occupying an elevated ocean bluff. Hand-plastered Venetian stucco, arched colonnades, and fragrant lavender gardens framing a resort-style infinity pool overlooking coastal sunsets.",
    highlights: [
      "Private gated motor court accommodating up to 10 vehicles",
      "Double-height rotunda foyer with floating wrought iron staircase",
      "Subterranean wine tasting room with 1,200 bottle climate storage",
      "Outdoor loggia with wood-fired pizza oven and alfresco dining pavilion",
    ],
    amenities: [
      "Resort Infinity Pool",
      "Outdoor Loggia Pavilion",
      "Motor Court with Fountain",
      "Subterranean Wine Vault",
      "Private Staff Quarters",
      "Smart Security Perimeter",
    ],
    features: {
      architecturalStyle: "Contemporary Coastal Mediterranean",
      view: "Panoramic Ocean Sunset & Coastal Bluffs",
      heatingCooling: "Multi-Zone Central HVAC",
      security: "Gated Estate with Private Guard Booth",
    },
    agent: {
      name: "Elena Rostova",
      role: "Senior Partner, Architectural Estates",
      phone: "+1 (555) 920-8422",
      email: "elena.rostova@lodhiestates.com",
      image: "/images/about.jpg",
    },
  },
];

export const NEIGHBORHOODS: Neighborhood[] = [
  {
    id: "nb-1",
    slug: "royal-gardens",
    name: "Royal Gardens",
    tagline: "Gated Heritage Groves & Private Sanctuaries",
    description:
      "Century-old tree canopies, 24/7 security patrols, championship equestrian grounds, and multi-acre secluded residences.",
    propertiesCount: 14,
    avgPriceSqFt: "$1,450 / sq ft",
    lifestyleRating: 9.8,
    image: "/images/neighborhood-1.jpg",
    highlights: [
      "Private Security Patrols & Gated Entry",
      "Championship Equestrian Club",
      "Top-Tier Academies within 5 mins",
      "Average lot size: 1.5–4.0 Acres",
    ],
  },
  {
    id: "nb-2",
    slug: "marina-bay",
    name: "Marina Bay",
    tagline: "Waterfront Splendor & Skyline High-Rise Living",
    description:
      "Deep-water yacht berths, Michelin-starred waterfront dining, designer boardwalks, and luxury high-rise penthouses.",
    propertiesCount: 28,
    avgPriceSqFt: "$1,820 / sq ft",
    lifestyleRating: 9.6,
    image: "/images/neighborhood-2.jpg",
    highlights: [
      "Deep-Water Berths up to 120ft",
      "Promenade with Michelin Star Dining",
      "High-speed Water Taxi to Finance Core",
      "Private Residents Sky Lounge",
    ],
  },
  {
    id: "nb-3",
    slug: "greenfield-estates",
    name: "Greenfield Estates",
    tagline: "Rolling Greens & Contemporary Modular Enclaves",
    description:
      "A serene architectural retreat combining wide rolling greens, bespoke contemporary architecture, and pristine air quality.",
    propertiesCount: 19,
    avgPriceSqFt: "$1,150 / sq ft",
    lifestyleRating: 9.4,
    image: "/images/neighborhood-3.jpg",
    highlights: [
      "Surrounded by 400 Acres Nature Preserve",
      "Championship Golf & Country Club",
      "Spacious 3,500–9,000 sq ft Custom Homes",
      "Fast 25-minute Highway Transit to City",
    ],
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "team-1",
    name: "Lord A. Lodhi",
    role: "Founder & Senior Principal",
    bio: "With over 30 years of global real estate leadership, Lord Lodhi has orchestrated more than $3.5B in landmark prime acquisitions across London, New York, and Dubai.",
    image: "/images/about.jpg",
    phone: "+1 (555) 920-8401",
    email: "lodhi@lodhiestates.com",
    specialization: "Ultra-High-Net-Worth Portfolio Advisory & Trophy Mansions",
    closedVolume: "$3.5 Billion+",
  },
  {
    id: "team-2",
    name: "Elena Rostova",
    role: "Senior Partner — Architectural & Coastal Estates",
    bio: "Recognized as a leading authority on modern architectural landmarks and private waterfront villas, Elena represents international art collectors and corporate founders.",
    image: "/images/about.jpg",
    phone: "+1 (555) 920-8422",
    email: "elena.rostova@lodhiestates.com",
    specialization: "Modernist Architecture & Coastal Promontories",
    closedVolume: "$850 Million+",
  },
  {
    id: "team-3",
    name: "Marcus Vance",
    role: "Managing Director — Prime Metropolitan Residences",
    bio: "Marcus commands an unmatched private network across major metropolitan luxury markets, securing premier pre-market penthouse allocations for private family offices.",
    image: "/images/about.jpg",
    phone: "+1 (555) 920-8411",
    email: "marcus.vance@lodhiestates.com",
    specialization: "Duplex Penthouses, Pre-War Restorations & Sky Towers",
    closedVolume: "$920 Million+",
  },
  {
    id: "team-4",
    name: "Julian Thorne",
    role: "Director — Turnkey Modular & Off-Market Assets",
    bio: "Specializing in discreet off-market transactions and sustainable modular estates, Julian advises clients on bespoke turnkey acquisitions with zero public footprint.",
    image: "/images/about.jpg",
    phone: "+1 (555) 920-8433",
    email: "julian.thorne@lodhiestates.com",
    specialization: "Discreet Off-Market Sourcing & Modular Developments",
    closedVolume: "$640 Million+",
  },
];

export const SERVICES: Service[] = [
  {
    id: "svc-1",
    title: "Bespoke Private Brokerage",
    tagline: "Exclusive Representation for High-Value Residences",
    description:
      "World-class marketing, private invitation-only previews, and global media placement across Architectural Digest and Financial Times.",
    icon: "Building2",
    features: [
      "Custom architectural film production & 3D scanning",
      "Direct outreach to vetted global family office networks",
      "Discreet NDA-bound private showing protocol",
      "Comprehensive structural and legal due diligence",
    ],
  },
  {
    id: "svc-2",
    title: "Discreet Off-Market Sourcing",
    tagline: "Unlocking Unlisted Architectural & Trophy Assets",
    description:
      "Over 45% of our closed transactions never appear on public portals. We leverage confidential relationships to source rare unlisted trophy estates.",
    icon: "Compass",
    features: [
      "Access to private family vaults and off-market estates",
      "Complete anonymity and strict buyer non-disclosure",
      "Strategic pricing intelligence and discrete negotiation",
      "Cross-border tax & legal structural advisory",
    ],
  },
  {
    id: "svc-3",
    title: "Architectural & Modular Advisory",
    tagline: "Turnkey Modular Homes & Renovation Advisory",
    description:
      "From bespoke modular construction delivered in 30–60 days to historic restorations, our team oversees design, permitting, and execution.",
    icon: "Layers",
    features: [
      "Precision-engineered Scandinavian modular residences",
      "Architectural planning and bespoke luxury interior fit-outs",
      "Turnkey procurement of designer furnishings & art",
      "Passivhaus net-zero and sustainable luxury retrofitting",
    ],
  },
  {
    id: "svc-4",
    title: "Portfolio Wealth Asset Management",
    tagline: "Long-term Wealth Preservation Through Real Estate",
    description:
      "Comprehensive multi-jurisdiction asset management, tenant vetting for diplomatic leases, and capital appreciation structuring.",
    icon: "TrendingUp",
    features: [
      "Yield optimization across prime residential holdings",
      "Turnkey property management and 24/7 VIP concierge desk",
      "Quarterly institutional valuation & equity modeling",
      "Estate succession and family governance handover",
    ],
  },
];

export const STATS: Stat[] = [
  {
    label: "Closed Volume",
    value: 3,
    prefix: "$",
    suffix: ".8B+",
    description: "In prime and trophy residential transactions",
  },
  {
    label: "Off-Market Exclusives",
    value: 45,
    suffix: "%",
    description: "Transactions closed without public listing",
  },
  {
    label: "Global HNW Clients",
    value: 1400,
    suffix: "+",
    description: "Families and private offices represented",
  },
  {
    label: "Years of Private Legacy",
    value: 26,
    suffix: " Yrs",
    description: "Established 1999 in prime markets",
  },
];

export const PRESS_MENTIONS = [
  { name: "Architectural Digest", quote: "Lodhi Estates defines the new standard of architectural living." },
  { name: "Forbes Global Properties", quote: "Ranked among the Top 5 Private Luxury Brokerages worldwide." },
  { name: "Financial Times", quote: "The secret address book for ultra-high-net-worth property acquisitions." },
  { name: "Robb Report", quote: "Pioneering the intersection of modern architecture and turnkey execution." },
];

export const OFFICES = [
  {
    city: "London",
    district: "Mayfair",
    address: "24 Berkeley Square, Mayfair, London W1J 6HE",
    phone: "+44 20 7946 0912",
    email: "london@lodhiestates.com",
    hours: "Mon – Fri: 8:30 AM – 6:30 PM",
  },
  {
    city: "New York",
    district: "Manhattan",
    address: "One Lodhi Plaza, 590 Madison Ave, New York, NY 10022",
    phone: "+1 (212) 555-0199",
    email: "ny@lodhiestates.com",
    hours: "Mon – Sat: 9:00 AM – 7:00 PM",
  },
  {
    city: "Dubai",
    district: "DIFC",
    address: "Gate Precinct 4, Level 7, DIFC, Dubai, UAE",
    phone: "+971 4 362 7000",
    email: "dubai@lodhiestates.com",
    hours: "Sun – Thu: 9:00 AM – 6:00 PM",
  },
  {
    city: "New Delhi",
    district: "Lodhi Estate",
    address: "12 Lodhi Estate, Amrita Shergill Marg, New Delhi 110003",
    phone: "+91 11 4150 8800",
    email: "delhi@lodhiestates.com",
    hours: "Mon – Sat: 9:30 AM – 6:30 PM",
  },
];

export const CONTACT_INFO = {
  phone: "+1 (555) 920-8400",
  email: "concierge@lodhiestates.com",
  address: "One Lodhi Plaza, 590 Madison Avenue, Suite 3200, New York, NY",
  hours: "Mon – Sat: 9:00 AM – 7:00 PM EST (24/7 Private VIP Desk)",
};
